service: bf3-metro-notifications

frameworkVersion: '2 | 3'

provider:
  name: aws
  stage: dev
  region: sa-east-1
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  httpApi:
    cors: true

plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: bf3.aws.hugo.dev.br
    endpointType: regional
    apiType: http
    createRoute53Record: false
    autoDomain: false

package:
  patterns:
    - node_modules/

functions:
  hello:
    handler: handler.hello
    memorySize: 128
    timeout: 5
    events:
      - httpApi:
          path: /
          method: get
